# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Pavluhina
                                 A QGIS plugin
 This plugin finds river (waterway=river)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-25
        copyright            : (C) 2025 by Pavluhina Sofia
        email                : .
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Pavluhina class from file Pavluhina.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Pavluhina import Pavluhina
    return Pavluhina(iface)
